In [22]:
import numpy as np

In [23]:
arr_2d = np.array([[5,10,15],[20,25,40], [12,455,21]])

In [24]:
arr_2d

array([[  5,  10,  15],
       [ 20,  25,  40],
       [ 12, 455,  21]])

In [28]:
arr_2d[0][0]

5

In [27]:
arr_2d[0]

array([ 5, 10, 15])

In [30]:
arr_2d[1][1]

25

In [31]:
arr_2d[2,1]

455

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 40]])

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
bool_arr = arr > 5

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [38]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [39]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr<3]

array([1, 2])