In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr # element by element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr * arr 

array([0, 1, 4, 9])

In [13]:
arr + 100

array([100, 101, 102, 103])

In [14]:
arr * 100

array([  0, 100, 200, 300])

In [15]:
1/0

ZeroDivisionError: division by zero

In [16]:
arr / arr

/Users/miguelsilvadarochajunior/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.])

In [17]:
1/arr

/Users/miguelsilvadarochajunior/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333])

In [18]:
arr ** 2

array([0, 1, 4, 9])

In [19]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081])

In [20]:
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692])

In [21]:
np.max(arr)

3

In [22]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001])